### ISSUE TITLE
Fuzz mariadb AFL crash in O3

### ISSUE THREAD

**Issue by zr950624** [Dobigthing666/Squirrel#9]
CMakeList:
```
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} -g -O3")
```

Command Line:
```
AFLplusplus/afl-fuzz -i data/fuzz_root/mysql_input/ -o output2 -- ./build/db_driver
```

env:
```
AFL_CUSTOM_MUTATOR_ONLY=1
HOSTNAME=c471508da0d7
AFL_DEBUG=1
AFL_MAP_SIZE=343719
PWD=/home/Squirrel
AFL_CUSTOM_MUTATOR_LIBRARY=/home/Squirrel/build/libmysql_mutator.so
HOME=/home
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SQUIRREL_CONFIG=/home/Squirrel/data/config_mysql.yml
AFL_FORKSRV_INIT_TMOUT=1000000
AFL_DISABLE_TRIM=1
OLDPWD=/home/Squirrel/build
_=/usr/bin/env
```

Crash backtrace:
```
#0  0x00007fc6ea49b5f4 in std::_Rb_tree_decrement(std::_Rb_tree_node_base*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007fc6ea710ed1 in std::_Rb_tree_iterator<std::pair<DATATYPE const, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::operator-- (this=<synthetic pointer>) at /usr/include/c++/11/bits/stl_tree.h:307
#2  Mutator::fill_one (this=0x55bef012b420, ir=<optimized out>) at /home/Squirrel/srcs/internal/mysql/srcs/mutator.cpp:952
#3  0x00007fc6ea7161dd in Mutator::fill_stmt_graph (this=0x55bef012b420, graph=std::map with 1 element = {...}) at /home/Squirrel/srcs/internal/mysql/srcs/mutator.cpp:816
#4  0x00007fc6ea7162e9 in Mutator::fix_one (this=0x55bef012b420, stmt_root=0x55bef4d51040, scope_library=std::map with 2 elements = {...}) at /home/Squirrel/srcs/internal/mysql/srcs/mutator.cpp:723
#5  0x00007fc6ea716540 in Mutator::fix (this=0x55bef012b420, root=<optimized out>) at /home/Squirrel/srcs/internal/mysql/srcs/mutator.cpp:651
#6  0x00007fc6ea7167ab in Mutator::validate (this=0x55bef012b420, root=@0x55bef40bc020: 0x55bef4d514f0) at /home/Squirrel/srcs/internal/mysql/srcs/mutator.cpp:606
#7  0x00007fc6ea6bcc2c in MySQLDB::validate_all (this=0x55bef0127e70, ir_set=...) at /usr/include/c++/11/bits/unique_ptr.h:173
#8  0x00007fc6ea6bd0c4 in MySQLDB::mutate (this=0x55bef0127e70, query=...) at /home/Squirrel/srcs/internal/mysql/mysql.cc:86
#9  0x00007fc6ea6b68ef in afl_custom_fuzz_count (mutator=0x55bef0127e70,
    buf=0x55bef400eba8 "CREATE TABLE v0 ( v1 INT , v2 INT NOT NULL , v3 INT , v4 INT NOT NULL ) ;\nINSERT INTO v0 VALUES ( 0 , 0 , 0 ) , ( 0 , 0 , 0 ) ;\nselect a from b where c = 3;\ndrop table v0;\n",
    buf_size=<optimized out>) at /home/Squirrel/srcs/custom_mutator.cc:45
#10 0x000055beee3e8bec in fuzz_one_original (afl=0x7fc6eb493010) at src/afl-fuzz-one.c:1877
#11 0x000055beee3d5195 in fuzz_one (afl=<optimized out>) at src/afl-fuzz-one.c:5712
#12 main (argc=<optimized out>, argv_orig=<optimized out>, envp=<optimized out>) at src/afl-fuzz.c:2531
```

**Comment by Changochen** [comment]
Fix by putting the `iter--` after the break.
